#!/system/bin/sh
MODDIR="$(cd "${0%/*}/.." 2>/dev/null && pwd)"
CFGDIR="$MODDIR/config"
APPS="$CFGDIR/apps.tsv"
ADV="$CFGDIR/advanced.kdl"
OUT="$CFGDIR/threadctl.kdl"
TMP="$CFGDIR/threadctl.kdl.tmp.$$"

mkdir -p "$CFGDIR"
[ -f "$APPS" ] || : > "$APPS"
[ -f "$ADV" ] || : > "$ADV"

{
  echo '// Generated by ThreadCtl-rs WebUI wrapper.'
  echo '// The daemon reading this file is the unmodified upstream threadctl-rs binary.'
  echo '// ---- WebUI managed app/profile rules ----'

  TAB="$(printf '\t')"
  while IFS="$TAB" read -r PKG PROFILE REST; do
    [ -n "$PKG" ] || continue
    case "$PKG" in
      *[!A-Za-z0-9._]*) continue ;;
    esac
    case "$PROFILE" in
      game|chat|video|launcher|audio|balanced|power-save) ;;
      *) continue ;;
    esac
    printf 'app "%s" { profile "%s" }\n' "$PKG" "$PROFILE"
  done < "$APPS"

  echo
  echo '// ---- Advanced raw KDL (preserved verbatim) ----'
  cat "$ADV"
  echo
} > "$TMP" || { rm -f "$TMP"; exit 1; }

chmod 0644 "$TMP" 2>/dev/null || true
mv -f "$TMP" "$OUT"
echo "[$(date '+%F %T')] rebuilt $OUT"
