#!/system/bin/sh
MODDIR="$(cd "${0%/*}/.." 2>/dev/null && pwd)"
CFG="$MODDIR/config"
mkdir -p "$CFG" "$MODDIR/run"
AUTO="$CFG/auto-apps.tsv"
OVR="$CFG/overrides.tsv"
EXC="$CFG/exclude.txt"
ADV="$CFG/advanced.kdl"
OUT="$CFG/threadctl.kdl"
TMP="$OUT.tmp.$$"

[ -f "$AUTO" ] || : > "$AUTO"
[ -f "$OVR" ] || : > "$OVR"
[ -f "$EXC" ] || : > "$EXC"
[ -f "$ADV" ] || : > "$ADV"

{
  echo "// Generated by ThreadCtl-rs Auto WebUI."
  echo "// Native daemon source is unmodified; this file is normal upstream KDL."
  echo "// Auto-discovered apps:"

  TAB="$(printf '\t')"
  while IFS="$TAB" read -r PKG BASE REASON LASTSEEN; do
    [ -n "$PKG" ] || continue
    echo "$PKG" | grep -Eq '^[A-Za-z0-9_]+([.][A-Za-z0-9_]+)+$' || continue
    grep -Fxq "$PKG" "$EXC" 2>/dev/null && continue

    PROFILE="$BASE"
    OV="$(awk -F '\t' -v p="$PKG" '$1==p {v=$2} END{print v}' "$OVR" 2>/dev/null)"
    [ -n "$OV" ] && PROFILE="$OV"
    case "$PROFILE" in
      game|chat|video|launcher|audio|balanced|power-save) ;;
      *) PROFILE="balanced" ;;
    esac
    printf 'app "%s" { profile "%s" }\n' "$PKG" "$PROFILE"
  done < "$AUTO"

  echo
  echo "// ---- Optional user advanced KDL follows unchanged ----"
  cat "$ADV" 2>/dev/null
  echo
} > "$TMP" || exit 1

mv -f "$TMP" "$OUT"
exit 0
